openapi: 3.0.3
info:
  title: View Template Management System API
  description: API for storing and retrieving view templates for users, using MongoDB as the database.
  version: 1.0.0
servers:
  - url: https://api.example.com

paths:
  /viewTemplates/{viewTemplateId}:
    get:
      summary: Get a specific view template
      parameters:
        - name: viewTemplateId
          in: path
          required: true
          schema:
            type: string
          description: ID of the view template to retrieve
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewTemplate'
        '403':
          description: Forbidden. Template is private to owner.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Template not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Update a specific view template
      parameters:
        - name: viewTemplateId
          in: path
          required: true
          schema:
            type: string
          description: ID of the view template to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewTemplateUpdate'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewTemplate'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden. Template is private to owner.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Template not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a specific view template
      parameters:
        - name: viewTemplateId
          in: path
          required: true
          schema:
            type: string
          description: ID of the view template to delete
      responses:
        '200':
          description: Success
        '403':
          description: Forbidden. Template is private to owner.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Template not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /viewTemplates/active:
    get:
      summary: Get the active view template for a contextView
      parameters:
        - name: contextView
          in: query
          required: true
          schema:
            type: string
          description: The contextView to retrieve the active view template for
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewTemplate'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: contextView not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /viewTemplates:
    post:
      summary: Create a new view template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewTemplateCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewTemplateId'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /viewTemplates/search:
    post:
      summary: Search for view templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewTemplateSearch'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ViewTemplate'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ViewTemplate:
      type: object
      properties:
        viewTemplateId:
          type: string
        companyId:
          type: integer
        contextView:
          type: string
        name:
          type: string
        description:
          type: string
        isPrivateToOwner:
          type: boolean
        isDefaultViewInContext:
          type: boolean
        createdDate:
          type: string
          format: date-time
        createdBy:
          $ref: '#/components/schemas/User'
        owner:
          $ref: '#/components/schemas/User'
        lastUpdatedDate:
          type: string
          format: date-time
        lastUpdatedBy:
          $ref: '#/components/schemas/User'
        view:
          type: object
    ViewTemplateUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        isPrivateToOwner:
          type: boolean
        isDefaultViewInContext:
          type: boolean
        view:
          type: object
    ViewTemplateCreate:
      type: object
      required:
        - contextView
        - name
        - view
      properties:
        contextView:
          type: string
        name:
          type: string
        description:
          type: string
        view:
          type: object
        isPrivateToOwner:
          type: boolean
          default: false
        isDefaultViewInContext:
          type: boolean
          default: false
    ViewTemplateSearch:
      type: object
      required:
        - filter
      properties:
        filter:
          type: object
    ViewTemplateId:
      type: object
      properties:
        viewTemplateId:
          type: string
    User:
      type: object
      properties:
        userId:
          type: integer
        displayName:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string

  responses:
    ViewTemplateNotFound:
      description: Template not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden. Template is private to owner.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Success:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ViewTemplate'
    Created:
      description: Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ViewTemplateId'
      
  parameters:
    viewTemplateId:
      name: viewTemplateId
      in: path
      required: true
      schema:
        type: string
      description: ID of the view template to retrieve, update, or delete.
    contextView:
      name: contextView
      in: query
      required: true
      schema:
        type: string
      description: The contextView to retrieve the active view template for.

tags:
  - name: ViewTemplates
    description: Operations related to view templates
